### ISSUE TITLE
with Readme "code" item in each algorithm point to .class file not .kt file 

### ISSUE THREAD

**Issue by MahmoudMabrok** [ahmedsamir9/Sorting-and-Searching-Algorithms-in-kotlin#1]
- with each video should **"code"** point to code file such as **.kt** 
- also it should be to view file not to download file

**Comment by ahmedsamir9** [comment]
Dear mr Mohammed
Thank you for told me about this issue the issue is solved , can you make a code review to help me improve my coding skills please
Best regards
